name: pandas_vs_koalas
channels:
  - conda-forge
dependencies:
  - arrow-cpp
  - cython
  - htop
  - ipyparallel
  - koalas
  - openjdk
  - pandas
  - pip
  - pyarrow
  - python=3.7
  - pyspark
  - pip:
    - gsutil
