name: pandas_vs_koalas
channels:
  - conda-forge
dependencies:
  - arrow-cpp
  - cython
  - google-cloud-storage
  - openjdk
  - pandas
  - pip
  - pyarrow
  - python=3.7
  - pyspark
  - pip:
    - ipyparallel
    - koalas
